export interface ElementDef {
  id: string;
  name: string;
  icon: string;
  color: string;
}

export const BASE_ELEMENTS: Record<string, ElementDef> = {
  water: { id: "water", name: "Água", icon: "💧", color: "bg-blue-600 text-white" },
  fire: { id: "fire", name: "Fogo", icon: "🔥", color: "bg-red-600 text-white" },
  earth: { id: "earth", name: "Terra", icon: "🌍", color: "bg-amber-700 text-white" },
  air: { id: "air", name: "Ar", icon: "🌬️", color: "bg-sky-400 text-slate-900" },
};

export const PREDEFINED_ELEMENTS: Record<string, ElementDef> = {
  ...BASE_ELEMENTS,
  steam: { id: "steam", name: "Vapor", icon: "💨", color: "bg-slate-300 text-slate-800" },
  mud: { id: "mud", name: "Lama", icon: "💩", color: "bg-amber-900 text-white" },
  lake: { id: "lake", name: "Lago", icon: "🌊", color: "bg-blue-500 text-white" },
  rain: { id: "rain", name: "Chuva", icon: "🌧️", color: "bg-blue-400 text-slate-900" },
  lava: { id: "lava", name: "Lava", icon: "🌋", color: "bg-orange-600 text-white" },
  energy: { id: "energy", name: "Energia", icon: "⚡", color: "bg-yellow-400 text-slate-900" },
  smoke: { id: "smoke", name: "Fumaça", icon: "🌫️", color: "bg-slate-500 text-white" },
  mountain: { id: "mountain", name: "Montanha", icon: "⛰️", color: "bg-stone-600 text-white" },
  dust: { id: "dust", name: "Poeira", icon: "🌪️", color: "bg-stone-400 text-slate-900" },
  wind: { id: "wind", name: "Vento", icon: "🍃", color: "bg-emerald-300 text-slate-900" },
  plant: { id: "plant", name: "Planta", icon: "🌱", color: "bg-green-500 text-white" },
  stone: { id: "stone", name: "Pedra", icon: "🪨", color: "bg-stone-500 text-white" },
  metal: { id: "metal", name: "Metal", icon: "🔩", color: "bg-slate-400 text-slate-900" },
  glass: { id: "glass", name: "Vidro", icon: "🪟", color: "bg-cyan-100 text-slate-900" },
  sand: { id: "sand", name: "Areia", icon: "🏜️", color: "bg-yellow-200 text-slate-800" },
  clay: { id: "clay", name: "Argila", icon: "🏺", color: "bg-orange-800 text-white" },
  brick: { id: "brick", name: "Tijolo", icon: "🧱", color: "bg-red-800 text-white" },
  house: { id: "house", name: "Casa", icon: "🏠", color: "bg-amber-100 text-slate-800" },
  village: { id: "village", name: "Vila", icon: "🏘️", color: "bg-amber-200 text-slate-800" },
  city: { id: "city", name: "Cidade", icon: "🏙️", color: "bg-slate-700 text-white" },
  country: { id: "country", name: "País", icon: "🗺️", color: "bg-blue-800 text-white" },
  continent: { id: "continent", name: "Continente", icon: "🌎", color: "bg-green-700 text-white" },
  planet: { id: "planet", name: "Planeta", icon: "🪐", color: "bg-indigo-900 text-white" },
  star: { id: "star", name: "Estrela", icon: "⭐", color: "bg-yellow-300 text-slate-900" },
  sun: { id: "sun", name: "Sol", icon: "☀️", color: "bg-orange-500 text-white" },
  moon: { id: "moon", name: "Lua", icon: "🌙", color: "bg-slate-200 text-slate-800" },
  life: { id: "life", name: "Vida", icon: "🧬", color: "bg-pink-400 text-white" },
  human: { id: "human", name: "Humano", icon: "👤", color: "bg-rose-200 text-slate-900" },
  bird: { id: "bird", name: "Pássaro", icon: "🐦", color: "bg-sky-500 text-white" },
  fish: { id: "fish", name: "Peixe", icon: "🐟", color: "bg-blue-400 text-white" },
  animal: { id: "animal", name: "Animal", icon: "🐾", color: "bg-yellow-600 text-white" },
  tree: { id: "tree", name: "Árvore", icon: "🌳", color: "bg-green-700 text-white" },
  forest: { id: "forest", name: "Floresta", icon: "🌲", color: "bg-green-900 text-white" },
  wood: { id: "wood", name: "Madeira", icon: "🪵", color: "bg-amber-800 text-white" },
  firewood: { id: "firewood", name: "Lenha", icon: "🔥", color: "bg-orange-700 text-white" },
  ash: { id: "ash", name: "Cinzas", icon: "⚪", color: "bg-slate-300 text-slate-800" },
  coal: { id: "coal", name: "Carvão", icon: "🪨", color: "bg-slate-900 text-white" },
  diamond: { id: "diamond", name: "Diamante", icon: "💎", color: "bg-cyan-300 text-slate-900" },
  gold: { id: "gold", name: "Ouro", icon: "🪙", color: "bg-yellow-500 text-white" },
  time: { id: "time", name: "Tempo", icon: "⏳", color: "bg-purple-500 text-white" },
  space: { id: "space", name: "Espaço", icon: "🌌", color: "bg-indigo-950 text-white" },
  galaxy: { id: "galaxy", name: "Galáxia", icon: "🌀", color: "bg-fuchsia-900 text-white" },
  universe: { id: "universe", name: "Universo", icon: "🎇", color: "bg-slate-950 text-white" },
  ocean: { id: "ocean", name: "Oceano", icon: "🌊", color: "bg-blue-800 text-white" },
  cloud: { id: "cloud", name: "Nuvem", icon: "☁️", color: "bg-slate-100 text-slate-800" },
  storm: { id: "storm", name: "Tempestade", icon: "⛈️", color: "bg-slate-800 text-white" },
  electricity: { id: "electricity", name: "Eletricidade", icon: "🌩️", color: "bg-yellow-400 text-slate-900" },
  computer: { id: "computer", name: "Computador", icon: "💻", color: "bg-slate-300 text-slate-900" },
  internet: { id: "internet", name: "Internet", icon: "🌐", color: "bg-blue-600 text-white" },
  robot: { id: "robot", name: "Robô", icon: "🤖", color: "bg-slate-400 text-slate-900" },
  ai: { id: "ai", name: "Inteligência Artificial", icon: "🧠", color: "bg-purple-600 text-white" },
  love: { id: "love", name: "Amor", icon: "❤️", color: "bg-red-500 text-white" },
  heart: { id: "heart", name: "Coração", icon: "💕", color: "bg-rose-500 text-white" },
  blood: { id: "blood", name: "Sangue", icon: "🩸", color: "bg-red-700 text-white" },
  death: { id: "death", name: "Morte", icon: "💀", color: "bg-slate-900 text-white" },
  ghost: { id: "ghost", name: "Fantasma", icon: "👻", color: "bg-slate-100 text-slate-800" },
  zombie: { id: "zombie", name: "Zumbi", icon: "🧟", color: "bg-emerald-800 text-white" },
  vampire: { id: "vampire", name: "Vampiro", icon: "🧛", color: "bg-indigo-900 text-white" },
  magic: { id: "magic", name: "Magia", icon: "✨", color: "bg-fuchsia-500 text-white" },
  wizard: { id: "wizard", name: "Mago", icon: "🧙", color: "bg-indigo-700 text-white" },
  dragon: { id: "dragon", name: "Dragão", icon: "🐉", color: "bg-red-800 text-white" },
  alien: { id: "alien", name: "Alien", icon: "👽", color: "bg-green-400 text-slate-900" },
  spaceship: { id: "spaceship", name: "Nave Espacial", icon: "🚀", color: "bg-slate-300 text-slate-800" },
  sword: { id: "sword", name: "Espada", icon: "🗡️", color: "bg-slate-200 text-slate-800" },
  shield: { id: "shield", name: "Escudo", icon: "🛡️", color: "bg-amber-600 text-white" },
  knight: { id: "knight", name: "Cavaleiro", icon: "🏇", color: "bg-slate-400 text-slate-900" },
  castle: { id: "castle", name: "Castelo", icon: "🏰", color: "bg-stone-700 text-white" },
  king: { id: "king", name: "Rei", icon: "👑", color: "bg-yellow-500 text-white" },
  queen: { id: "queen", name: "Rainha", icon: "👸", color: "bg-pink-500 text-white" },
  princess: { id: "princess", name: "Princesa", icon: "👧", color: "bg-pink-300 text-slate-900" },
  bat: { id: "bat", name: "Morcego", icon: "🦇", color: "bg-slate-800 text-white" },
  wolf: { id: "wolf", name: "Lobo", icon: "🐺", color: "bg-slate-600 text-white" },
  werewolf: { id: "werewolf", name: "Lobisomem", icon: "🐺", color: "bg-stone-800 text-white" },
  cat: { id: "cat", name: "Gato", icon: "🐱", color: "bg-orange-300 text-slate-900" },
  dog: { id: "dog", name: "Cachorro", icon: "🐶", color: "bg-amber-700 text-white" },
  dinosaur: { id: "dinosaur", name: "Dinossauro", icon: "🦖", color: "bg-green-800 text-white" },
  egg: { id: "egg", name: "Ovo", icon: "🥚", color: "bg-yellow-100 text-slate-800" },
  chicken: { id: "chicken", name: "Galinha", icon: "🐔", color: "bg-amber-100 text-slate-900" },
  feather: { id: "feather", name: "Pena", icon: "🪶", color: "bg-slate-100 text-slate-800" },
  angel: { id: "angel", name: "Anjo", icon: "👼", color: "bg-blue-100 text-slate-800" },
  demon: { id: "demon", name: "Demônio", icon: "👿", color: "bg-red-900 text-white" },
  hell: { id: "hell", name: "Inferno", icon: "🔥", color: "bg-red-950 text-white" },
  heaven: { id: "heaven", name: "Paraíso", icon: "☁️", color: "bg-cyan-100 text-slate-800" },
  god: { id: "god", name: "Deus", icon: "👁️", color: "bg-yellow-200 text-slate-900" },
  religion: { id: "religion", name: "Religião", icon: "🛐", color: "bg-purple-800 text-white" },
  book: { id: "book", name: "Livro", icon: "📖", color: "bg-amber-900 text-white" },
  library: { id: "library", name: "Biblioteca", icon: "📚", color: "bg-amber-800 text-white" },
  knowledge: { id: "knowledge", name: "Conhecimento", icon: "🧠", color: "bg-indigo-500 text-white" },
  science: { id: "science", name: "Ciência", icon: "🔬", color: "bg-blue-300 text-slate-900" },
  math: { id: "math", name: "Matemática", icon: "➗", color: "bg-emerald-600 text-white" },
  money: { id: "money", name: "Dinheiro", icon: "💵", color: "bg-green-600 text-white" },
  bank: { id: "bank", name: "Banco", icon: "🏦", color: "bg-stone-300 text-slate-900" },
  capitalism: { id: "capitalism", name: "Capitalismo", icon: "📈", color: "bg-yellow-600 text-white" },
  communism: { id: "communism", name: "Comunismo", icon: "☭", color: "bg-red-700 text-white" },
  war: { id: "war", name: "Guerra", icon: "⚔️", color: "bg-red-900 text-white" },
  peace: { id: "peace", name: "Paz", icon: "🕊️", color: "bg-cyan-200 text-slate-800" },
  music: { id: "music", name: "Música", icon: "🎵", color: "bg-pink-600 text-white" },
  art: { id: "art", name: "Arte", icon: "🎨", color: "bg-purple-500 text-white" },
  painting: { id: "painting", name: "Pintura", icon: "🖼️", color: "bg-yellow-200 text-slate-800" },
  color: { id: "color", name: "Cor", icon: "🌈", color: "bg-gradient-to-r from-red-500 via-green-500 to-blue-500 text-white" },
  light: { id: "light", name: "Luz", icon: "💡", color: "bg-yellow-300 text-slate-900" },
  darkness: { id: "darkness", name: "Escuridão", icon: "🌑", color: "bg-black text-white" },
  shadow: { id: "shadow", name: "Sombra", icon: "👤", color: "bg-slate-800 text-white" },
  mirror: { id: "mirror", name: "Espelho", icon: "🪞", color: "bg-cyan-100 text-slate-800" },
  ice: { id: "ice", name: "Gelo", icon: "🧊", color: "bg-sky-200 text-slate-900" },
  snow: { id: "snow", name: "Neve", icon: "❄️", color: "bg-white text-slate-900 border border-slate-200" },
  snowman: { id: "snowman", name: "Boneco de Neve", icon: "☃️", color: "bg-white text-slate-900 border border-slate-200" },
  winter: { id: "winter", name: "Inverno", icon: "🥶", color: "bg-blue-300 text-slate-900" },
  summer: { id: "summer", name: "Verão", icon: "🥵", color: "bg-orange-400 text-white" },
  beach: { id: "beach", name: "Praia", icon: "🏖️", color: "bg-yellow-200 text-slate-800" },
  beer: { id: "beer", name: "Cerveja", icon: "🍺", color: "bg-amber-400 text-slate-900" },
  wine: { id: "wine", name: "Vinho", icon: "🍷", color: "bg-rose-900 text-white" },
  drunk: { id: "drunk", name: "Bêbado", icon: "🥴", color: "bg-green-500 text-white" },
  sleep: { id: "sleep", name: "Sono", icon: "😴", color: "bg-indigo-800 text-white" },
  dream: { id: "dream", name: "Sonho", icon: "💭", color: "bg-purple-300 text-slate-900" },
  nightmare: { id: "nightmare", name: "Pesadelo", icon: "😱", color: "bg-purple-900 text-white" },
  idea: { id: "idea", name: "Ideia", icon: "💡", color: "bg-yellow-400 text-slate-900" },
  invention: { id: "invention", name: "Invenção", icon: "⚙️", color: "bg-slate-400 text-slate-900" },
  wheel: { id: "wheel", name: "Roda", icon: "🛞", color: "bg-stone-500 text-white" },
  car: { id: "car", name: "Carro", icon: "🚗", color: "bg-red-500 text-white" },
  engine: { id: "engine", name: "Motor", icon: "🔧", color: "bg-slate-600 text-white" },
  train: { id: "train", name: "Trem", icon: "🚂", color: "bg-stone-800 text-white" },
  airplane: { id: "airplane", name: "Avião", icon: "✈️", color: "bg-blue-300 text-slate-900" },
};

const RAW_PREDEFINED_RECIPES: Record<string, string> = {
  // Basics
  "fire,water": "steam",
  "earth,water": "mud",
  "water,water": "lake",
  "air,water": "rain",
  "earth,fire": "lava",
  "fire,fire": "energy",
  "air,fire": "smoke",
  "earth,earth": "mountain",
  "air,earth": "dust",
  "air,air": "wind",
  // Simple compounds
  "earth,rain": "plant",
  "plant,water": "tree",
  "tree,tree": "forest",
  "lava,water": "stone",
  "air,stone": "sand",
  "fire,sand": "glass",
  "mud,sand": "clay",
  "clay,fire": "brick",
  "fire,stone": "metal",
  // Civilization
  "brick,brick": "house",
  "house,house": "village",
  "village,village": "city",
  "city,city": "country",
  "country,country": "continent",
  "continent,continent": "planet",
  "planet,planet": "star",
  "fire,star": "sun",
  "stone,sun": "moon",
  // Biology
  "energy,water": "life",
  "earth,life": "plant",
  "life,mud": "animal",
  "animal,forest": "bird",
  "animal,lake": "fish",
  "animal,earth": "human",
  // Tools & Materials
  "human,metal": "computer",
  "computer,computer": "internet",
  "computer,life": "robot",
  "computer,human": "ai",
  "tree,tool": "wood",
  "fire,wood": "firewood",
  "fire,firewood": "ash",
  "earth,wood": "coal",
  "coal,time": "diamond",
  "metal,sun": "gold",
  // Cosmic
  "star,star": "galaxy",
  "galaxy,galaxy": "universe",
  "space,time": "universe",
  "planet,sun": "space",
  "lake,lake": "ocean",
  "air,steam": "cloud",
  "cloud,wind": "storm",
  "energy,storm": "electricity",
  // Mythological
  "human,love": "heart",
  "human,human": "love",
  "heart,water": "blood",
  "human,time": "death",
  "death,life": "ghost",
  "death,human": "zombie",
  "blood,human": "vampire",
  "energy,life": "magic",
  "human,magic": "wizard",
  "animal,magic": "dragon",
  "animal,fire": "dragon",
  
  // NEW RECIPES
  "human,space": "alien",
  "metal,space": "spaceship",
  "metal,magic": "sword",
  "metal,wood": "sword",
  "sword,metal": "shield",
  "human,sword": "knight",
  "house,stone": "castle",
  "human,castle": "king",
  "king,love": "queen",
  "king,queen": "princess",
  "bird,night": "bat",
  "dog,moon": "wolf",
  "human,wolf": "werewolf",
  "animal,house": "cat",
  "wolf,bone": "dog",
  "animal,time": "dinosaur",
  "bird,time": "dinosaur",
  "bird,bird": "egg",
  "egg,life": "chicken",
  "bird,death": "feather",
  "human,bird": "angel",
  "human,heaven": "angel",
  "human,hell": "demon",
  "fire,death": "hell",
  "cloud,love": "heaven",
  "universe,life": "god",
  "god,human": "religion",
  "wood,knowledge": "book",
  "book,book": "library",
  "human,book": "knowledge",
  "knowledge,universe": "science",
  "knowledge,number": "math",
  "gold,paper": "money",
  "house,money": "bank",
  "money,money": "capitalism",
  "capitalism,revolution": "communism",
  "human,death": "war",
  "war,time": "peace",
  "art,sound": "music",
  "human,color": "art",
  "color,brush": "painting",
  "light,water": "color",
  "sun,glass": "light",
  "light,time": "darkness",
  "light,human": "shadow",
  "glass,silver": "mirror",
  "glass,light": "mirror",
  "water,cold": "ice",
  "rain,cold": "snow",
  "snow,human": "snowman",
  "snow,time": "winter",
  "sun,time": "summer",
  "ocean,sand": "beach",
  "water,wheat": "beer",
  "water,grape": "wine",
  "beer,human": "drunk",
  "drunk,time": "sleep",
  "sleep,life": "dream",
  "dream,death": "nightmare",
  "knowledge,time": "idea",
  "idea,metal": "invention",
  "invention,wood": "wheel",
  "wheel,metal": "car",
  "car,fire": "engine",
  "car,train": "train",
  "metal,bird": "airplane",
  "water,wind": "wave",
  "wave,earth": "tsunami",
  "earth,wind": "dust",
  "dust,water": "mud",
  "mud,life": "bacteria",
};

export const PREDEFINED_RECIPES: Record<string, string> = {};
for (const [key, value] of Object.entries(RAW_PREDEFINED_RECIPES)) {
  const sortedKey = key.split(",").sort().join(",");
  PREDEFINED_RECIPES[sortedKey] = value;
}