export enum ElementType {
  EMPTY = 'empty',
  SAND = 'sand',
  WATER = 'water',
  STONE = 'stone',
  WOOD = 'wood',
  FIRE = 'fire',
  SMOKE = 'smoke',
  OIL = 'oil',
  GAS = 'gas',
  STEAM = 'steam',
  LAVA = 'lava',
  ICE = 'ice',
  PLANT = 'plant',
  ACID = 'acid',
  METAL = 'metal',
  GUNPOWDER = 'gunpowder',
  NITRO = 'nitro',
  SALT = 'salt',
  CLAY = 'clay',
  FUNGUS = 'fungus',
  GLASS = 'glass',
  DIRT = 'dirt',
  SNOW = 'snow',
  COAL = 'coal',
  ASH = 'ash',
  SEED = 'seed',
  SLIME = 'slime',
  HONEY = 'honey',
  SPARK = 'spark',
  WIRE = 'wire',
  SPONGE = 'sponge',
  VIRUS = 'virus',
  NEON = 'neon',
  RUST = 'rust',
  C4 = 'c4',
  THERMITE = 'thermite',
  BLOOD = 'blood',

  // --- NEW ELEMENTS ---
  IRON = 'iron',
  COPPER = 'copper',
  GOLD = 'gold',
  MERCURY = 'mercury',
  VINE = 'vine',
  SPORE = 'spore',
  BACTERIA = 'bacteria',
  ANT = 'ant',
  TERMITE = 'termite',
  MEAT = 'meat',
  BONE = 'bone',
  PLASMA = 'plasma',
  ELECTRICITY = 'electricity',
  VOID = 'void',
  ANTIMATTER = 'antimatter',
  BLACK_HOLE = 'black_hole',
  POISON = 'poison',
  ALCOHOL = 'alcohol',
  LIQUID_NITROGEN = 'liquid_nitrogen',
  DIAMOND = 'diamond',
  OBSIDIAN = 'obsidian',
  PAPER = 'paper',
  WAX = 'wax',
  CLOUD = 'cloud',
  OXYGEN = 'oxygen',
  HYDROGEN = 'hydrogen',
  HELIUM = 'helium',
  BATTERY = 'battery',
  LIGHTBULB = 'lightbulb',
  NUKE = 'nuke',
  DUST = 'dust',
  GRAVEL = 'gravel',
  URANIUM = 'uranium',

  RANDOM = 'random',
}

export interface ElementProperties {
  type: ElementType;
  color: string;
  density: number; // For floating/sinking
  state: 'solid' | 'liquid' | 'gas' | 'immobile' | 'energy';
  flammable?: boolean;
  burnRate?: number;
  lifetime?: number;
  explosive?: boolean;
  viscosity?: number; // For liquids like honey/slime
}

export const ELEMENTS: Record<ElementType, ElementProperties> = {
  [ElementType.EMPTY]: { type: ElementType.EMPTY, color: '#000000', density: 0, state: 'gas' },
  [ElementType.SAND]: { type: ElementType.SAND, color: '#f2d16b', density: 10, state: 'solid' },
  [ElementType.WATER]: { type: ElementType.WATER, color: '#4fa4f4', density: 5, state: 'liquid' },
  [ElementType.STONE]: { type: ElementType.STONE, color: '#888888', density: 100, state: 'immobile' },
  [ElementType.WOOD]: { type: ElementType.WOOD, color: '#7a5230', density: 20, state: 'immobile', flammable: true, burnRate: 0.05 },
  [ElementType.FIRE]: { type: ElementType.FIRE, color: '#ff4500', density: 1, state: 'energy', lifetime: 50 },
  [ElementType.SMOKE]: { type: ElementType.SMOKE, color: '#444444', density: 0.1, state: 'gas', lifetime: 100 },
  [ElementType.OIL]: { type: ElementType.OIL, color: '#3b3b1f', density: 4, state: 'liquid', flammable: true, burnRate: 0.4 },
  [ElementType.GAS]: { type: ElementType.GAS, color: '#aaffaa', density: 0.2, state: 'gas', flammable: true, burnRate: 0.8 },
  [ElementType.STEAM]: { type: ElementType.STEAM, color: '#ddddff', density: 0.1, state: 'gas', lifetime: 150 },
  [ElementType.LAVA]: { type: ElementType.LAVA, color: '#ff2200', density: 15, state: 'liquid' },
  [ElementType.ICE]: { type: ElementType.ICE, color: '#aaddff', density: 8, state: 'immobile' },
  [ElementType.PLANT]: { type: ElementType.PLANT, color: '#2d5a27', density: 12, state: 'immobile', flammable: true, burnRate: 0.1 },
  [ElementType.ACID]: { type: ElementType.ACID, color: '#7cfc00', density: 6, state: 'liquid' },
  [ElementType.METAL]: { type: ElementType.METAL, color: '#b0bcc5', density: 200, state: 'immobile' },
  [ElementType.GUNPOWDER]: { type: ElementType.GUNPOWDER, color: '#555555', density: 11, state: 'solid', flammable: true, burnRate: 1.0, explosive: true },
  [ElementType.NITRO]: { type: ElementType.NITRO, color: '#00ff00', density: 3, state: 'liquid', flammable: true, burnRate: 1.0, explosive: true },
  [ElementType.SALT]: { type: ElementType.SALT, color: '#ffffff', density: 9, state: 'solid' },
  [ElementType.CLAY]: { type: ElementType.CLAY, color: '#9e5a3c', density: 15, state: 'solid' },
  [ElementType.FUNGUS]: { type: ElementType.FUNGUS, color: '#7b4b94', density: 1, state: 'immobile' },
  [ElementType.GLASS]: { type: ElementType.GLASS, color: '#90CBE5', density: 100, state: 'immobile' },
  [ElementType.DIRT]: { type: ElementType.DIRT, color: '#4a3018', density: 10, state: 'solid' },
  [ElementType.SNOW]: { type: ElementType.SNOW, color: '#eeeeff', density: 2, state: 'solid' },
  [ElementType.COAL]: { type: ElementType.COAL, color: '#222222', density: 15, state: 'immobile', flammable: true, burnRate: 0.02 },
  [ElementType.ASH]: { type: ElementType.ASH, color: '#b2b5b5', density: 3, state: 'solid' },
  [ElementType.SEED]: { type: ElementType.SEED, color: '#aebf45', density: 9, state: 'solid' },
  [ElementType.SLIME]: { type: ElementType.SLIME, color: '#50c878', density: 6, state: 'liquid', viscosity: 0.8 },
  [ElementType.HONEY]: { type: ElementType.HONEY, color: '#ffb300', density: 7, state: 'liquid', viscosity: 0.9, flammable: true, burnRate: 0.05 },
  [ElementType.SPARK]: { type: ElementType.SPARK, color: '#ffff00', density: 0, state: 'energy', lifetime: 10 },
  [ElementType.WIRE]: { type: ElementType.WIRE, color: '#d87e36', density: 80, state: 'immobile' },
  [ElementType.SPONGE]: { type: ElementType.SPONGE, color: '#f5da42', density: 10, state: 'immobile' },
  [ElementType.VIRUS]: { type: ElementType.VIRUS, color: '#ff00ff', density: 4, state: 'solid' },
  [ElementType.NEON]: { type: ElementType.NEON, color: '#ff00aa', density: 0.1, state: 'gas' },
  [ElementType.RUST]: { type: ElementType.RUST, color: '#8a3324', density: 12, state: 'solid' },
  [ElementType.C4]: { type: ElementType.C4, color: '#dddddd', density: 20, state: 'immobile', explosive: true },
  [ElementType.THERMITE]: { type: ElementType.THERMITE, color: '#b93b3b', density: 15, state: 'solid' },
  [ElementType.BLOOD]: { type: ElementType.BLOOD, color: '#aa0000', density: 6, state: 'liquid' },

  [ElementType.IRON]: { type: ElementType.IRON, color: '#7a7a7a', density: 100, state: 'immobile' },
  [ElementType.COPPER]: { type: ElementType.COPPER, color: '#b87333', density: 95, state: 'immobile' },
  [ElementType.GOLD]: { type: ElementType.GOLD, color: '#ffd700', density: 110, state: 'immobile' },
  [ElementType.MERCURY]: { type: ElementType.MERCURY, color: '#c0c0c0', density: 18, state: 'liquid' },
  [ElementType.VINE]: { type: ElementType.VINE, color: '#006400', density: 3, state: 'immobile', flammable: true },
  [ElementType.SPORE]: { type: ElementType.SPORE, color: '#dda0dd', density: 0.05, state: 'gas' },
  [ElementType.BACTERIA]: { type: ElementType.BACTERIA, color: '#9acd32', density: 0.5, state: 'solid' },
  [ElementType.ANT]: { type: ElementType.ANT, color: '#111111', density: 1, state: 'solid' },
  [ElementType.TERMITE]: { type: ElementType.TERMITE, color: '#a0522d', density: 1, state: 'solid' },
  [ElementType.MEAT]: { type: ElementType.MEAT, color: '#ff6347', density: 5, state: 'solid', flammable: true },
  [ElementType.BONE]: { type: ElementType.BONE, color: '#ffdead', density: 15, state: 'immobile' },
  [ElementType.PLASMA]: { type: ElementType.PLASMA, color: '#ff00ff', density: 0, state: 'energy', explosive: true },
  [ElementType.ELECTRICITY]: { type: ElementType.ELECTRICITY, color: '#ffff00', density: 0, state: 'energy' },
  [ElementType.VOID]: { type: ElementType.VOID, color: '#111111', density: 0, state: 'immobile' },
  [ElementType.ANTIMATTER]: { type: ElementType.ANTIMATTER, color: '#330033', density: 1, state: 'solid', explosive: true },
  [ElementType.BLACK_HOLE]: { type: ElementType.BLACK_HOLE, color: '#050505', density: 9999, state: 'immobile' },
  [ElementType.POISON]: { type: ElementType.POISON, color: '#8b008b', density: 7, state: 'liquid' },
  [ElementType.ALCOHOL]: { type: ElementType.ALCOHOL, color: '#e8e8ed', density: 4.8, state: 'liquid', explosive: true, flammable: true, burnRate: 1.0 },
  [ElementType.LIQUID_NITROGEN]: { type: ElementType.LIQUID_NITROGEN, color: '#e0ffff', density: 5.5, state: 'liquid' },
  [ElementType.DIAMOND]: { type: ElementType.DIAMOND, color: '#b9f2ff', density: 200, state: 'immobile' },
  [ElementType.OBSIDIAN]: { type: ElementType.OBSIDIAN, color: '#1a1a1a', density: 150, state: 'immobile' },
  [ElementType.PAPER]: { type: ElementType.PAPER, color: '#e1e1e1', density: 1, state: 'solid', flammable: true, burnRate: 0.9 },
  [ElementType.WAX]: { type: ElementType.WAX, color: '#f0e68c', density: 3, state: 'solid', flammable: true, burnRate: 0.05 },
  [ElementType.CLOUD]: { type: ElementType.CLOUD, color: '#fbfbfb', density: -1, state: 'gas' },
  [ElementType.OXYGEN]: { type: ElementType.OXYGEN, color: '#b0e0e6', density: -1, state: 'gas' },
  [ElementType.HYDROGEN]: { type: ElementType.HYDROGEN, color: '#afeeee', density: -2, state: 'gas', explosive: true, flammable: true },
  [ElementType.HELIUM]: { type: ElementType.HELIUM, color: '#ffffe0', density: -3, state: 'gas' },
  [ElementType.BATTERY]: { type: ElementType.BATTERY, color: '#2e8b57', density: 60, state: 'immobile' },
  [ElementType.LIGHTBULB]: { type: ElementType.LIGHTBULB, color: '#f0f0f0', density: 10, state: 'immobile' },
  [ElementType.NUKE]: { type: ElementType.NUKE, color: '#556b2f', density: 80, state: 'immobile', explosive: true },
  [ElementType.DUST]: { type: ElementType.DUST, color: '#a9a9a9', density: 4, state: 'solid' },
  [ElementType.GRAVEL]: { type: ElementType.GRAVEL, color: '#696969', density: 20, state: 'solid' },
  [ElementType.URANIUM]: { type: ElementType.URANIUM, color: '#16a085', density: 80, state: 'solid' },

  [ElementType.RANDOM]: { type: ElementType.RANDOM, color: 'linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet)', density: 0, state: 'energy' },
};
